var GAME_LEVELS = [
["                                                     ",
 "               @                                     ",
 "    tttt ttttt ott  tt   ttttt               ",
 "    t      t   t  t t t    t                  ",
  "    t      t   t  t t t    t                 ",
 "xx  tttt   t   tttt ttt    t                  ",
 "x      t   t   t  t t  t   t                ",
 "x      t   t   t  t t  t   t                  ",
 "x   tttt   t   t  t t  t   t               xx ",
 "x                                                 x ",
 "x                                                 x ",
 "x                                                 x ",
 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "],                 
  ["                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                 xx  ",
   "  xx                  o                       o   o                              x  ",
   "  x                  xx                         e                                x  ",
   "  x           e               e               xxxxx          o                   x  ",
   "  x          xxxx          xxxxxx                                       e        ox  ",
   "  x  @       x  x!!!!!!!!!!x    x o         e         e                xxxxx       x  ",
   "  xxxxxxxxxxxx  x!!!!!!!!!!x    xxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxx    xx  ",
   "                xxxxxxxxxxxx       x   x                  x     x           x    x   ",
   "                                   x!!!x                  x!!!!!x           x    x   ",
   "                                   x!!!x                  x!!!!!x           x    x   ",
   "                                   xxxxx                  xxxxxxx           x    x   ",
   "                                         xx                                 x    x   ",
   "                                         x                                  x    x   ",
   "                                         x                                       x   ",
   "                                         x        o          o       o          ox   ",
   "                                         x       xxx        xxx      xxx   xxxxxx  ",
   "                                         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   ",
   "                                         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   ",
   "                                         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   ",
   "                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                     ",
   "                                                                                    x "],
  ["                                                                                    x ",
   "                                                                                    x ",
   "                                                                                    x ",
   "                                                                                    x ",
   "                           x          o                                             x ",
   "                          x!x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       x ",
   "                           v         x                                              x  ",
   "                    x            o   x                                              x  ",
   "                   x!x =        xx   x                                              x  ",
   "                    v                x                                              x  ",
   "                           o         x                                              x  ",
   "                          xx         x                                              x  ",
   "                                     x                                              x  ",
   "                     o               x          xx                                  x    ",
   "  xxxxxxxxx =       xx               x          xo                                  x  ",
   "  x                                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x  @                               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                     "],
   [" @ o           ",
   "xxxxxxxxxxxxxxx"],
   [" @ o           ",
   "xxxxxxxxxxxxxxx"],
   [" @ o           ",
   "xxxxxxxxxxxxxxx"],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
